name: push-base-image
on:
  push:
    # branches:
    #   - base-image

jobs:
  image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/waltid-walletkit:latest
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/waltid-walletkit:latest
          cache-to: type=inline
          build-args: |
            SKIP_TESTS=true
